name: Octo Organization CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1


      - name: Run a one-line script
        run: echo Hello from Octo Organization

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        env:
          UPDATE_TYPE : patch
          BRANCH : ${BRSNCH_NAME}
        run: |
          python bump_version.py