name: GithubAction | PR dev to release


on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sync-branch"
  sync-branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo content
          uses: actions/checkout@master # checkout the repository content to github runner.
                  - name: setup python
                  uses: actions/setup-python@v2
                  with:
                    python-version: 3.8 #install the python needed
                  - name: execute py script # run the run.py to get the latest data
                    run: |
                      UPDATE_TYPE=patch python bump_version.py
